### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary item

### ISSUE THREAD

**Issue by WolfBV** [TeraV8/Techniphilia-Core#1]
https://pastebin.com/CMZfDmyQ

**Comment by TeraV8** [comment]
What version of Forge are you using? And what other mods?
Or, just post complete log/crash report

**Comment by WolfBV** [comment]
[message.txt](https://github.com/TeraV8/Techniphilia-Core/files/8492310/message.txt)

message.txt is their latest.log

Forge version 14.23.5.2860

Reporting this issue in place of https://github.com/Mysticpasta1 because they're busy rn. They're using 900+ mods

**Comment by TeraV8** [comment]
[The fix has been released here](https://www.curseforge.com/minecraft/mc-mods/techniphilia-core/files/3751851)
